# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inst.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ninst.proto\x12\x0cProtoMessage"P\n\nInstHeader\x12\x0e\n\x06obj_id\x18\x01 \x02(\t\x12\x0e\n\x03ver\x18\x02 \x02(\r:\x01\x30\x12\x11\n\ttick_freq\x18\x03 \x02(\x04\x12\x0f\n\x07has_mem\x18\x04 \x02(\x08"\xbf\x06\n\x04Inst\x12\n\n\x02pc\x18\x01 \x02(\x04\x12\x0c\n\x04inst\x18\x02 \x01(\x07\x12\x12\n\ninst_bytes\x18\t \x01(\x0c\x12\x0e\n\x06nodeid\x18\x03 \x01(\r\x12\r\n\x05\x63puid\x18\x04 \x01(\r\x12\x0c\n\x04tick\x18\x05 \x01(\x06\x12)\n\x04type\x18\x06 \x01(\x0e\x32\x1b.ProtoMessage.Inst.InstType\x12\x12\n\ninst_flags\x18\x07 \x01(\r\x12\x30\n\nmem_access\x18\x08 \x03(\x0b\x32\x1c.ProtoMessage.Inst.MemAccess\x1a:\n\tMemAccess\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x02(\x04\x12\x0c\n\x04size\x18\x02 \x02(\r\x12\x11\n\tmem_flags\x18\x03 \x01(\r"\xae\x04\n\x08InstType\x12\x08\n\x04None\x10\x00\x12\n\n\x06IntAlu\x10\x01\x12\n\n\x06IntMul\x10\x02\x12\n\n\x06IntDiv\x10\x03\x12\x0c\n\x08\x46loatAdd\x10\x04\x12\x0c\n\x08\x46loatCmp\x10\x05\x12\x0c\n\x08\x46loatCvt\x10\x06\x12\r\n\tFloatMult\x10\x07\x12\x0c\n\x08\x46loatDiv\x10\x08\x12\r\n\tFloatSqrt\x10\t\x12\x0e\n\nSIMDIntAdd\x10\n\x12\x11\n\rSIMDIntAddAcc\x10\x0b\x12\x0e\n\nSIMDIntAlu\x10\x0c\x12\x0e\n\nSIMDIntCmp\x10\r\x12\x0e\n\nSIMDIntCvt\x10\x0e\x12\x0c\n\x08SIMDMisc\x10\x0f\x12\x0f\n\x0bSIMDIntMult\x10\x10\x12\x12\n\x0eSIMDIntMultAcc\x10\x11\x12\x10\n\x0cSIMDIntShift\x10\x12\x12\x13\n\x0fSIMDIntShiftAcc\x10\x13\x12\x0c\n\x08SIMDSqrt\x10\x14\x12\x10\n\x0cSIMDFloatAdd\x10\x15\x12\x10\n\x0cSIMDFloatAlu\x10\x16\x12\x10\n\x0cSIMDFloatCmp\x10\x17\x12\x10\n\x0cSIMDFloatCvt\x10\x18\x12\x10\n\x0cSIMDFloatDiv\x10\x19\x12\x11\n\rSIMDFloatMisc\x10\x1a\x12\x11\n\rSIMDFloatMult\x10\x1b\x12\x14\n\x10SIMDFloatMultAdd\x10\x1c\x12\x11\n\rSIMDFloatSqrt\x10\x1d\x12\x0b\n\x07MemRead\x10\x1e\x12\x0c\n\x08MemWrite\x10\x1f\x12\r\n\tIprAccess\x10 \x12\x10\n\x0cInstPrefetch\x10!'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inst_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _INSTHEADER._serialized_start = 28
    _INSTHEADER._serialized_end = 108
    _INST._serialized_start = 111
    _INST._serialized_end = 942
    _INST_MEMACCESS._serialized_start = 323
    _INST_MEMACCESS._serialized_end = 381
    _INST_INSTTYPE._serialized_start = 384
    _INST_INSTTYPE._serialized_end = 942
# @@protoc_insertion_point(module_scope)
